export const AUTOMATIK_COPY = {
  tabLabel: 'Automatik',
  panelHeading: 'Turnier-Automatik',
  panelDescription:
    'Presets pflegen, Vorschläge prüfen und Turniere manuell aus einem Preset einplanen.',
  presetsHeading: 'Presets',
  presetsEmpty: 'Noch keine Presets angelegt.',
  presetCreateButton: 'Neues Preset',
  presetEditButton: 'Bearbeiten',
  presetDeleteButton: 'Löschen',
  presetActivateButton: 'Aktivieren',
  presetDeactivateButton: 'Deaktivieren',
  presetDeleteConfirm: 'Dieses Preset wirklich löschen?',
  presetActive: 'Aktiv',
  presetInactive: 'Inaktiv',
  presetInfoLabel: 'Eckdaten',
  presetFormCreateHeading: 'Neues Preset',
  presetFormEditHeading: 'Preset bearbeiten',
  presetFormCancel: 'Abbrechen',
  presetFormSave: 'Speichern',
  nameLabel: 'Name',
  categoryLabel: 'Kategorie',
  categoryFun: 'Fun',
  categoryComp: 'Comp',
  teamSizeLabel: 'Teamgröße',
  bracketFormatLabel: 'Bracket-Format',
  bracketSingle: 'Single Elimination',
  bracketDouble: 'Double Elimination',
  seriesFormatLabel: 'Serienformat',
  seriesBo1: 'Bo1',
  seriesBo3: 'Bo3',
  seriesBo5: 'Bo5',
  finalSeriesFormatLabel: 'Finalformat',
  finalSeriesSame: 'Wie Serienformat',
  tournamentModeLabel: 'Turniermodus',
  tournamentModeGroupStage: 'Gruppenphase',
  tournamentModeBracketOnly: 'Nur Bracket',
  gameModeLabel: 'Spielmodus',
  gameModeStandard: 'Standard',
  gameModeMirror: 'Mirror Match',
  gameModeAllSame: 'All Same Hero',
  gameModeRandomHeroes: 'Random Heroes',
  gameModeSingleLane: 'Single Lane',
  matchObjectiveLabel: 'Match-Wertung',
  inviteModeLabel: 'Einladungs-Modus',
  inviteAlways: 'Immer erlaubt',
  inviteWindow: 'Nur im Zeitfenster',
  inviteNever: 'Deaktiviert (Auto-Balance)',
  reminderOffsetsLabel: 'Reminder vor Turnier-Start (Minuten)',
  startReminderOffsetsLabel: 'Erinnerung vor Match-Start (Minuten)',
  rulesLabel: 'Regelwerk',
  descriptionTemplateLabel: 'Beschreibungs-Vorlage',
  activeCheckboxLabel: 'Preset aktiv',
  proposalsHeading: 'Vorschläge',
  proposalsEmpty: 'Noch keine Vorschläge vorhanden.',
  manualHeading: 'Manuell einplanen',
  presetSelectLabel: 'Preset',
  proposedStartLabel: 'Geplanter Start',
  manualCreateButton: 'Vorschlag anlegen',
  proposalDetailHeading: 'Vorschlag-Details',
  proposalSelectHint:
    'Wähle links einen Vorschlag, um Details, Votes und Feedback zu sehen.',
  proposalStateLabel: 'Status',
  proposalSourceLabel: 'Herkunft',
  proposalCreatedLabel: 'Erstellt',
  proposalPresetLabel: 'Preset',
  proposalApprovalsLabel: 'Freigaben',
  proposalConfigLabel: 'Konfiguration (JSON)',
  submitEvent: 'Zur Freigabe',
  approveEvent: 'Annehmen',
  rejectEvent: 'Ablehnen',
  expireEvent: 'Verfallen lassen',
  votesHeading: 'Votes',
  feedbackHeading: 'Feedback',
  feedbackPlaceholder: 'Änderungswunsch notieren …',
  feedbackSubmit: 'Feedback speichern',
  voteCasterLabel: 'Caster-Discord-ID',
  voteDecisionLabel: 'Entscheidung',
  voteApprove: 'Annehmen',
  voteReject: 'Ablehnen',
  voteSubmit: 'Vote speichern',
  sourceBot: 'Bot',
  sourceManual: 'Manuell',
  stateDraft: 'Entwurf',
  statePendingApproval: 'Freigabe offen',
  stateApproved: 'Angenommen',
  stateRejected: 'Abgelehnt',
  stateExpired: 'Verfallen',
  noPresetOption: 'Preset wählen …',
} as const
