[Service]
WorkingDirectory=/home/nathanael/repos/Deadlock-Turniere
EnvironmentFile=
ExecStart=
ExecStart=/home/nathanael/repos/Deadlock-Turniere/scripts/run_turniere_backend_rust.sh --config /home/nathanael/repos/Deadlock-Turniere/config/bot.toml
ExecReload=
